### ISSUE TITLE
Bug in readme: data can not be an object

### ISSUE THREAD

**Issue by pke** [andywer/http-event-stream#11]
The sample code in the readme is faulty. The `data` field is to be expected an array or a single value but not an object like shown. `sendEvent` will fail when trying to call `replace` on the data item (objects don't have a replace method).

**Comment by andywer** [comment]
Thanks, @pke! Will fix the readme accordingly 👍

**Comment by pke** [comment]
Or fix the implementation to `JSON.stringify` data if its an object?
I'd prefer that, since its a valid and common use case. What do you think?

**Comment by andywer** [comment]
I thought about it, too, but that smells like trouble. Consider the following scenario:

```
sendEvent({
  data: userSuppliedPayload
})
```

Now I cannot easily `JSON.parse()` on the other end, because if `userSuppliedPayload` was a string then it didn't get `JSON.stringify()`-ed.

Or we always `JSON.stringify()`, but then you are not in control of the data format you send anymore.

Or we let you opt-out from `JSON.stringify()`...

**Comment by pke** [comment]
Well data can be only a number, string, array, object or (async) function.
Could be all allowed and converted to string.
If its a function its resolved and the return value converted to string. Since sendEvent iself is async, such function could also async.

so all could be valid:

```js
sendEvent({
  async data() { await userSuppliedPayload }
})

sendEvent({
  data: 1
})

sendEvent({
  data: "string"
})

sendEvent({
  data: [1, "string", async () => await userSuppliedPayload]
})
```

But I am not sure if that does not bloat the API surface of this lib too much. Maybe there is already a `toString` package out there that would handle all those inputs.

**Comment by andywer** [comment]
Honestly, I don't even think this is a good idea in the first place... A simple `JSON.stringify()` as a default should be ok if you have a way to opt out, but everything beyond that cannot be considered an implementation of default behavior anymore.

Passing a function, for instance, can in many scenarios be a good indicator that your code is broken and you accidentally passed some function instead of calling it. So trying to serialize everything that you throw at it might very easily turn into an anti-feature 😉

Btw, at the end of the day all you can possibly submit via SSEs is text data. So let's try to not obfuscate that basic unchangeable fact too much 🙂

**Comment by pke** [comment]
I am all for keeping the API surface simple. Why do you support `string[]` though?
I would like to add a type check before "assuming" the data property is a string or string array though.

[Here](https://github.com/andywer/http-event-stream/blob/master/src/stream.ts#L52) it should do a

```js
if (typeof itemData !== "string) {
  throw new TypeError(data.length > 1 ? `data[${index}] must be a string, but it is ${typeof itemData}` : `data must be a string, but it is ${typeof itemData}`);
}
```

**Comment by andywer** [comment]
I think it’s specified somewhere in here: <https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation>

An event can have multiple `data` fields. Since multiple data fields are supposed to be appended it’s debatable if the string array will really ever yield a real-life benefit, though... 🤔
